# Simple workflow for previewing GitHub Pages before merging a PR
name: Deploy PR Pages preview

on:
  # Runs on pushes targeting the gh-pages branch
  push:
    branches: ["gh-pages"]
  pull_request:
    types:
        - opened
        - synchronize

jobs:
  # Single deploy job since we're just deploying
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.6.1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            preview-branch: gh-pages
            source-dir: .
            umbrella-dir: pr-preview
            action: auto
