# Simple workflow for previewing GitHub Pages before merging a PR
name: Deploy PR Pages preview

on:
  # Runs on pushes targeting the gh-pages branch
  push:
    branches: ["gh-pages"]
  pull_request:
    types:
        - opened
        - synchronize
  workflow_dispatch:
    branches: ["gh-pages"]
    inputs:
      pr_number:
        description: Pull request number to preview
        required: true
        type: string

jobs:
  # Single deploy job since we're just deploying
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set PR number for manual run
        if: github.event_name == 'workflow_dispatch'
        run: echo "pr_number=${{ github.event.inputs.pr_number }}" >> "$GITHUB_ENV"
      - name: Set PR number from event
        if: github.event_name == 'pull_request'
        run: echo "pr_number=${{ github.event.pull_request.number }}" >> "$GITHUB_ENV"
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.6.1
        env:
            pr_number: ${{ env.pr_number }}
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            preview-branch: gh-pages
            source-dir: .
            umbrella-dir: pr-preview
            action: auto